### ISSUE TITLE
Tutorials `ModuleNotFoundError`

### ISSUE THREAD

**Issue by IaroslavElistratov** [themis-ai/capsa#110]
[This change](https://github.com/themis-ai/capsa/commit/ea96bc2e5bfe18a2ec70298b416bc80d9ab9c0ec#diff-2feaf05c163c20c153b1c35fb50871a19c1145d67d99271a2d412f163a790fa3L12) causes `ModuleNotFoundError` and therefore makes the depth notebooks not runnable.

**Comment by IaroslavElistratov** [comment]
@fynnsu

**Comment by fynnsu** [comment]
Hi @IaroslavElistratov, thanks for pointing this out. I've updated the import, so should be working now

**Comment by IaroslavElistratov** [comment]
@aamini I think we need to publish new version of the package on pip such that the change is reflected in the tutorials, is it correct?

**Comment by aamini** [comment]
Thanks both -- I just pushed a new version to pypi: https://pypi.org/project/capsa/0.1.4/

`pip install capsa` should auto pull this new version.
