### ISSUE TITLE
Some errors from Part2_BiasAndUncertainty notebook

### ISSUE THREAD

**Issue by kennylids** [themis-ai/capsa#128]
1.
![image](https://user-images.githubusercontent.com/76207555/236403692-3dc8081e-2956-4767-b500-76782834130c.png)
It's a quick fix for me and there is some adjustment after., as such
![image](https://user-images.githubusercontent.com/76207555/236404017-49a911a7-8a82-40b1-8faf-9668a9aa5183.png)

2. This is an error I dont know how to solve. 
![image](https://user-images.githubusercontent.com/76207555/236404237-dae2f336-2acf-4655-9cb3-57f907acef05.png)

**Comment by kennylids** [comment]
The notebook is from MIT Deep Learning course, link as follows:
https://github.com/aamini/introtodeeplearning/blob/master/lab3/Part2_BiasAndUncertainty.ipynb

**Comment by kennylids** [comment]
The notebook is from MIT Deep Learning course, link as follows:
https://github.com/aamini/introtodeeplearning/blob/master/lab3/Part2_BiasAndUncertainty.ipynb

**Comment by egesko** [comment]
Since those notebooks were published, we've updated capsa wrappers to always output risk tensors. So, it's expected for those notebooks to not be up to date. Tagging @aamini

**Comment by egesko** [comment]
[Fixed](https://github.com/aamini/introtodeeplearning/pull/129#event-9234312467)
