### ISSUE TITLE
Predicting y_hat

### ISSUE THREAD

**Issue by IaroslavElistratov** [themis-ai/capsa#23]
In the `ControllerWrapper`'s `call()` don't output multiple y_hat's (one from each metric) but take their mean and variance and output those as y_hat -- this would give us another uncertainty metric in addition to all our metrics. In other words, we can make our y_hat more robust at a relatively low cost (relative to some of our metrics like RandNets and VAEs that require a whole new model to run) because here in each case, in each metric we're adding only 1 more layer on top of the extracted features.

Alternatively, predict y_hat in the controller wrapper only once with an additional layer (copy of user's last layer) instead of predicting y_hat in each metric and averaging it (as suggested in the first paragraph of this issue).

**Comment by egesko** [comment]
Closing the issue as it's not applicable anymore.
