### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by aamini** [themis-ai/capsa#40]
- [x] (@IaroslavElistratov) aleatoric classification
- [ ] (@egesko) Toy example for both classification and regression (2 tutorials) -- recreates fig 1 from capsa paper
  - low dim bias (KDE and histogram)
- [ ] Composability (dataset TBD)
- [ ] (@IaroslavElistratov) Injected dataset noise into mnist and uncovering the uncertainty (aleatoric)
- [x] (@IaroslavElistratov) Monocular Depth Estimation (rgb -> depth)
  - Anomaly detection
  - Adversarial?

**Comment by IaroslavElistratov** [comment]
Unassigning myself since the depth tutorials has been added.
