### ISSUE TITLE
Update the histogram wrapper

### ISSUE THREAD

**Issue by IaroslavElistratov** [themis-ai/capsa#43]
#33 addressed [the following issues](https://github.com/themis-ai/capsa/pull/33#issuecomment-1269068338) although in this PR there are still a few things left to do for the histogram wrapper: 1. reduce code duplication by reusing call() in loss_fn() 2. add docstrings 3. make sure all of the relevant tests work for this wrapper

**Comment by aamini** [comment]
Done and merged
