### ISSUE TITLE
Colab support for tutorials

### ISSUE THREAD

**Issue by aamini** [themis-ai/capsa#50]
Currently tutorials are in the form of jupyter ipynb notebooks. It would be nice to also support colab directly so users can quickly try out the code without needing to download/install any dependencies. 

It seems like this should need only minor changes to the notebooks but I think it might need to happen after we make the repo open-source (or at least after we add to PyPi) so we can access it from colab.

**Comment by IaroslavElistratov** [comment]
Closing as completed?
